Use limits.h instead of syslimits.h
Regression found by tinderbox in 89b3485dadef47a30264a5bf150b96522183376b

xcb_util.c:31:27: error: sys/syslimits.h: No such file or directory
xcb_util.c: In function '_xcb_open':
xcb_util.c:148: error: 'PATH_MAX' undeclared (first use in this function)

Signed-off-by: Jeremy Huddleston <jeremyhu@apple.com>